// Next.js Components
import Head from 'next/head'

// Providers Imports
import { Providers } from './providers'

// Global Styles imports
import '@/styles/login.css'

export const metadata = {
  title: 'Login Page',
  description: 'Generated by Next.js',
}

// Component Declaration
export default function Layout({ children }) {
  // Return components, with functions to call API and language
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
      </Head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
  //
}
