import Head from 'next/head'

import '@/styles/login.css'
import { Providers } from './providers'

export const metadata = {
  title: 'Login Page',
  description: 'Generated by Next.js',
}

export default function Layout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/favicon.ico" />
        <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
      </Head>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
